
print("\033[1;32mPlease enter the metabolizer statusus of your patients phenotypes below.")
print("\033[1;37m \n")
CYP2D6 = input("CYP2D6 phenotype (ex. PM, IM, NM, RM, UM): ")
CYP2C19 = input("CYP2C19 phenotype (ex. PM, IM, NM, RM, UM): ")

if CYP2D6 == "PM" and CYP2C19 == "PM":
    print("Only 0.08% of people phenotype as a poor metabolizer for CYP2D6 as well as CYP2C19!")
    print("It's recommended to use psychotropic medication that's neither metabolized by CYP2D6 nor CYP2C19.")
    print("The following atypical antipsychotics are suggested: Clozapine, Olanzapine, and Quetiapine.")
    print(" ")
    print("The following SSRIs are suggested: Escitalopram, and Citalopram.")
    print("The following mood stabilizers are suggested: Lithium.")
    print("The following benzodiazepines are suggested: Lorazepam, and Oxazepam.")

if CYP2D6 == "PM" and CYP2C19 == "IM":
    print("Only 0.4% of people have this specific metabolizer phenotype!")
    print("It's recommended to use psychotropic medication that's neither metabolized by CYP2D6 nor CYP2C19.")
    print(" ")
    print("The following atypical antipsychotics are suggested: Clozapine, Olanzapine, and Quetiapine.")
    print("The following SSRIs are suggested: Escitalopram, and Citalopram.")
    print("The following mood stabilizers are suggested: Lithium.")
    print("The following benzodiazepines are suggested: Lorazepam, and Oxazepam.")

if CYP2D6 == "PM" and CYP2C19 == "NM":
    print("Only 2.2% of people have this specific metabolizer phenotype!")
    print("It's recommended to avoid psychotropic medication that's metabolized by CYP2D6.")
    print(" ")
    print("The following suggestions are metabolized by CYP2C19:")
    print("SSRIs: Fluoxetine, and Sertraline.")
    print("Tricyclic antidepressants: Amitriptyline, and Imipramine.")
    print("Anticonvulsants: Phenytoin, and Valproic Acid.")
    print(" ")
    print("Or if you prefer to stay on the safe side, it's suggested to prescribe medication that's neither metabolized by CYP2D6 nor CYP2C19.")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")

if CYP2D6 == "PM" and CYP2C19 == "RM":
    print("Only 0.8% of people have this specific metabolizer phenotype!")
    print("It's recommended to avoid psychotropic medication that's metabolized by CYP2D6.")
    print("Due to the fact that the patient is an RM metabolizer for CYP2C19, dose adjustment is possible, but it is much easier to prescribe another type of medication to avoid side effects.")
    print(" ")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")

if CYP2D6 == "PM" and CYP2C19 == "UM":
    print("Only 0.04% of people have this specific metabolizer phenotype!")
    print("It's recommended to avoid psychotropic medication that's metabolized by CYP2D6.")
    print("Due to the fact that the patient is an UM metabolizer for CYP2C19, dose adjustment is possible, but it is much easier to prescribe another type of medication to avoid side effects.")
    print(" ")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")

if CYP2D6 == "IM" and CYP2C19 == "PM":
    print("Only 0.9% of people have this specific metabolizer phenotype!")
    print("It's recommended to use psychotropic medication that's neither metabolized by CYP2D6 nor CYP2C19.")
    print(" ")
    print("The following atypical antipsychotics are suggested: Clozapine, Olanzapine, and Quetiapine.")
    print("The following SSRIs are suggested: Escitalopram, and Citalopram.")
    print("The following mood stabilizers are suggested: Lithium.")
    print("The following benzodiazepines are suggested: Lorazepam, and Oxazepam.")

if CYP2D6 == "IM" and CYP2C19 == "IM":
    print("Only 6% of people have this specific metabolizer phenotype!")
    print("It's recommended to use psychotropic medication that's neither metabolized by CYP2D6 nor CYP2C19.")
    print(" ")
    print("The following atypical antipsychotics are suggested: Clozapine, Olanzapine, and Quetiapine.")
    print("The following SSRIs are suggested: Escitalopram, and Citalopram.")
    print("The following mood stabilizers are suggested: Lithium.")
    print("The following benzodiazepines are suggested: Lorazepam, and Oxazepam.")

if CYP2D6 == "IM" and CYP2C19 == "NM":
    print("Only 16% of people have this specific metabolizer phenotype!")
    print("It's recommended to avoid psychotropic medication that's metabolized by CYP2D6.")
    print(" ")
    print("The following suggestions are metabolized by CYP2C19:")
    print("SSRIs: Fluoxetine, and Sertraline.")
    print("Tricyclic antidepressants: Amitriptyline, and Imipramine.")
    print("Anticonvulsants: Phenytoin, and Valproic Acid.")
    print(" ")
    print("Or if you prefer to stay on the safe side, it's suggested to prescribe medication that's neither metabolized by CYP2D6 nor CYP2C19.")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")

if CYP2D6 == "IM" and CYP2C19 == "RM":
    print("Only 9.8% of people have this specific metabolizer phenotype!")
    print("It's recommended to avoid psychotropic medication that's metabolized by CYP2D6.")
    print("Due to the fact that the patient is an RM metabolizer for CYP2C19, dose adjustment is possible, but it is much easier to prescribe another type of medication to avoid side effects.")
    print(" ")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")

if CYP2D6 == "IM" and CYP2C19 == "UM":
    print("Only 1.7% of people have this specific metabolizer phenotype!")
    print("It's recommended to avoid psychotropic medication that's metabolized by CYP2D6.")
    print("Due to the fact that the patient is an UM metabolizer for CYP2C19, dose adjustment is possible, but it is much easier to prescribe another type of medication to avoid side effects.")
    print(" ")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")

if CYP2D6 == "NM" and CYP2C19 == "PM":
    print("Only 1.4% of people have this specific metabolizer phenotype!")
    print("It's recommended to avoid psychotropic medication that's metabolized by CYP2C19.")
    print(" ")
    print("The following suggestions are metabolized by CYP2D6:")
    print("Tricyclic antidepressants: Amitriptyline, Clomipramine, and Imipramine.")
    print("SSRIs: Fluoxetine, Paroxetine, and Sertraline.")
    print("Atypical antipsychotics: Risperidone, and Ziprasidone.")
    print("Beta Blockers: Propanolol, and Metoprolol.")
    print("Opioid analgesics: Codeine, Hydrocodone, and Oxycodone.")

if CYP2D6 == "NM" and CYP2C19 == "IM":
    print("Only 11.5% of people have this specific metabolizer phenotype!")
    print("It's recommended to avoid psychotropic medication that's metabolized by CYP2C19.")
    print(" ")
    print("The following suggestions are metabolized by CYP2D6:")
    print("Tricyclic antidepressants: Amitriptyline, Clomipramine, and Imipramine.")
    print("SSRIs: Fluoxetine, Paroxetine, and Sertraline.")
    print("Atypical antipsychotics: Risperidone, and Ziprasidone.")
    print("Beta Blockers: Propanolol, and Metoprolol.")
    print("Opioid analgesics: Codeine, Hydrocodone, and Oxycodone.")

if CYP2D6 == "NM" and CYP2C19 == "NM":
    print("Only 30.3% of people have this specific metabolizer phenotype!")
    print("This specific phenotype allows the most freedom within prescribing psychotropic medication.")
    print(" ")
    print("The following suggestions are metabolized by CYP2D6:")
    print("Tricyclic antidepressants: Amitriptyline, Clomipramine, and Imipramine.")
    print("SSRIs: Fluoxetine, Paroxetine, and Sertraline.")
    print("Atypical antipsychotics: Risperidone, and Ziprasidone.")
    print("Beta Blockers: Propanolol, and Metoprolol.")
    print("Opioid analgesics: Codeine, Hydrocodone, and Oxycodone.")
    print(" ")
    print("The following suggestions are metabolized by CYP2C19:")
    print("SSRIs: Fluoxetine, and Sertraline.")
    print("Tricyclic antidepressants: Amitriptyline, and Imipramine.")
    print("Anticonvulsants: Phenytoin, and Valproic Acid.")
    print(" ")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")

if CYP2D6 == "NM" and CYP2C19 == "RM":
    print("Only 16.6% of people have this specific metabolizer phenotype!")
    print("It's recommended to avoid psychotropic medication that's metabolized by CYP2C19.")
    print("Due to the fact that the patient is an RM metabolizer for CYP2D6, dose adjustment is possible, but it is much easier to prescribe another type of medication to avoid side effects.")
    print(" ")
    print("The following suggestions are metabolized by CYP2D6:")
    print("Tricyclic antidepressants: Amitriptyline, Clomipramine, and Imipramine.")
    print("SSRIs: Fluoxetine, Paroxetine, and Sertraline.")
    print("Atypical antipsychotics: Risperidone, and Ziprasidone.")
    print("Beta Blockers: Propanolol, and Metoprolol.")
    print("Opioid analgesics: Codeine, Hydrocodone, and Oxycodone.")
    print(" ")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")

if CYP2D6 == "NM" and CYP2C19 == "UM":
    print("Only 2.5% of people have this specific metabolizer phenotype!")
    print("It's recommended to avoid psychotropic medication that's metabolized by CYP2C19.")
    print("Due to the fact that the patient is an UM metabolizer for CYP2D6, dose adjustment is possible, but it is much easier to prescribe another type of medication to avoid side effects.")
    print(" ")
    print("The following suggestions are metabolized by CYP2D6:")
    print("Tricyclic antidepressants: Amitriptyline, Clomipramine, and Imipramine.")
    print("SSRIs: Fluoxetine, Paroxetine, and Sertraline.")
    print("Atypical antipsychotics: Risperidone, and Ziprasidone.")
    print("Beta Blockers: Propanolol, and Metoprolol.")
    print("Opioid analgesics: Codeine, Hydrocodone, and Oxycodone.")
    print(" ")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")

if CYP2D6 == "RM" and CYP2C19 == "PM":
    print("No people with this specific metabolizer phenotype have resulted from the GROUP study, congrats you're special!")
    print("It's recommended to avoid psychotropic medication that's metabolized by CYP2C19.")
    print("Due to the fact that the patient is an RM metabolizer for CYP2D6, dose adjustment is possible, but it is much easier to prescribe another type of medication to avoid side effects.")
    print(" ")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")

if CYP2D6 == "RM" and CYP2C19 == "IM":
    print("No people with this specific metabolizer phenotype have resulted from the GROUP study, congrats you're special!")
    print("It's recommended to avoid psychotropic medication that's metabolized by CYP2C19.")
    print("Due to the fact that the patient is an RM metabolizer for CYP2D6, dose adjustment is possible, but it is much easier to prescribe another type of medication to avoid side effects.")
    print(" ")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")

if CYP2D6 == "RM" and CYP2C19 == "NM":
    print("No people with this specific metabolizer phenotype have resulted from the GROUP study, congrats you're special!")
    print("Due to the fact that the patient is an RM metabolizer for CYP2D6, dose adjustment is possible, but it is much easier to prescribe another type of medication to avoid side effects.")
    print(" ")
    print("The following suggestions are metabolized by CYP2C19:")
    print("SSRIs: Fluoxetine, and Sertraline.")
    print("Tricyclic antidepressants: Amitriptyline, and Imipramine.")
    print("Anticonvulsants: Phenytoin, and Valproic Acid.")
    print(" ")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")

if CYP2D6 == "RM" and CYP2C19 == "RM":
    print("No people with this specific metabolizer phenotype have resulted from the GROUP study, congrats you're special!")
    print("Due to the fact that the patient is an RM metabolizer for CYP2D6 as well as for CYP2C19, dose adjustment is possible, but it is much easier to prescribe another type of medication to avoid side effects.")
    print(" ")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")

if CYP2D6 == "UM" and CYP2C19 == "RM":
    print("No people with this specific metabolizer phenotype have resulted from the GROUP study, congrats you're special!")
    print("Due to the fact that the patient is an UM metabolizer for CYP2D6, dose adjustment is possible, but it is much easier to prescribe another type of medication to avoid side effects.")
    print("Due to the fact that the patient is an RM metabolizer for CYP2C19, dose adjustment is possible, but it is much easier to prescribe another type of medication to avoid side effects.")
    print(" ")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")

if CYP2D6 == "UM" and CYP2C19 == "UM":
    print("No people with this specific metabolizer phenotype have resulted from the GROUP study, congrats you're special!")
    print("Due to the fact that the patient is an UM metabolizer for CYP2D6 as well as for CYP2C19, dose adjustment is possible, but it is much easier to prescribe another type of medication to avoid side effects.")
    print(" ")
    print("The following suggestions are neither metabolized by CYP2D6 nor CYP2C19:")
    print("Atypical antipsychotics: Clozapine, Olanzapine, and Quetiapine.")
    print("SSRIs: Escitalopram, and Citalopram.")
    print("Mood stabilizers: Lithium.")
    print("Benzodiazepines: Lorazepam, and Oxazepam.")
